// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: proto/file/bucket.proto

package file

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建存储桶的请求
type BucketMakeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                  // 名称
	Capacity     uint64 `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`         // 初始容量
	Engine       Engine `protobuf:"varint,3,opt,name=engine,proto3,enum=Engine" json:"engine,omitempty"` // 存储引擎
	Address      string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`            // 存储引擎的地址
	Scope        string `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`                // 存储引擎的作用范围
	AccessKey    string `protobuf:"bytes,6,opt,name=accessKey,proto3" json:"accessKey,omitempty"`        // 存储引擎的访问key
	AccessSecret string `protobuf:"bytes,7,opt,name=accessSecret,proto3" json:"accessSecret,omitempty"`  // 存储引擎的访问secret
	Url          string `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`                    // 存储引擎的外部访问地址
}

func (x *BucketMakeRequest) Reset() {
	*x = BucketMakeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_bucket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketMakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketMakeRequest) ProtoMessage() {}

func (x *BucketMakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_bucket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketMakeRequest.ProtoReflect.Descriptor instead.
func (*BucketMakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_bucket_proto_rawDescGZIP(), []int{0}
}

func (x *BucketMakeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketMakeRequest) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *BucketMakeRequest) GetEngine() Engine {
	if x != nil {
		return x.Engine
	}
	return Engine_ENGINE_INVALID
}

func (x *BucketMakeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BucketMakeRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *BucketMakeRequest) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *BucketMakeRequest) GetAccessSecret() string {
	if x != nil {
		return x.AccessSecret
	}
	return ""
}

func (x *BucketMakeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 列举存储桶的回复
type BucketListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移值
	Count  int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`   // 数量
}

func (x *BucketListRequest) Reset() {
	*x = BucketListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_bucket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketListRequest) ProtoMessage() {}

func (x *BucketListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_bucket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketListRequest.ProtoReflect.Descriptor instead.
func (*BucketListRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_bucket_proto_rawDescGZIP(), []int{1}
}

func (x *BucketListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BucketListRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 列举存储桶的回复
type BucketListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Total  uint64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`  // 总数
	Entity []*BucketEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"` // 实体列表
}

func (x *BucketListResponse) Reset() {
	*x = BucketListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_bucket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketListResponse) ProtoMessage() {}

func (x *BucketListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_bucket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketListResponse.ProtoReflect.Descriptor instead.
func (*BucketListResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_bucket_proto_rawDescGZIP(), []int{2}
}

func (x *BucketListResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BucketListResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BucketListResponse) GetEntity() []*BucketEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 删除存储桶的请求
type BucketRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // uuid
}

func (x *BucketRemoveRequest) Reset() {
	*x = BucketRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_bucket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketRemoveRequest) ProtoMessage() {}

func (x *BucketRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_bucket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketRemoveRequest.ProtoReflect.Descriptor instead.
func (*BucketRemoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_bucket_proto_rawDescGZIP(), []int{3}
}

func (x *BucketRemoveRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 获取存储桶信息的请求
type BucketGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // uuid
}

func (x *BucketGetRequest) Reset() {
	*x = BucketGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_bucket_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketGetRequest) ProtoMessage() {}

func (x *BucketGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_bucket_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketGetRequest.ProtoReflect.Descriptor instead.
func (*BucketGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_bucket_proto_rawDescGZIP(), []int{4}
}

func (x *BucketGetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 获取存储桶信息的回复
type BucketGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Entity *BucketEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"` // 实体
}

func (x *BucketGetResponse) Reset() {
	*x = BucketGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_bucket_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketGetResponse) ProtoMessage() {}

func (x *BucketGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_bucket_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketGetResponse.ProtoReflect.Descriptor instead.
func (*BucketGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_bucket_proto_rawDescGZIP(), []int{5}
}

func (x *BucketGetResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BucketGetResponse) GetEntity() *BucketEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 查找一个存储桶信息的请求
type BucketFindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // name
}

func (x *BucketFindRequest) Reset() {
	*x = BucketFindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_bucket_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketFindRequest) ProtoMessage() {}

func (x *BucketFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_bucket_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketFindRequest.ProtoReflect.Descriptor instead.
func (*BucketFindRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_bucket_proto_rawDescGZIP(), []int{6}
}

func (x *BucketFindRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 查找一个存储桶信息的回复
type BucketFindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Entity *BucketEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"` // 实体
}

func (x *BucketFindResponse) Reset() {
	*x = BucketFindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_bucket_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketFindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketFindResponse) ProtoMessage() {}

func (x *BucketFindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_bucket_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketFindResponse.ProtoReflect.Descriptor instead.
func (*BucketFindResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_bucket_proto_rawDescGZIP(), []int{7}
}

func (x *BucketFindResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BucketFindResponse) GetEntity() *BucketEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 更新存储桶的请求
// 空值将不会被更新
type BucketUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid         string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                  // 桶的UUID
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                  // 名称
	Capacity     uint64 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`         // 初始容量
	Engine       Engine `protobuf:"varint,4,opt,name=engine,proto3,enum=Engine" json:"engine,omitempty"` // 存储引擎
	Address      string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`            // 存储引擎的地址
	Scope        string `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`                // 存储引擎的作用范围
	AccessKey    string `protobuf:"bytes,7,opt,name=accessKey,proto3" json:"accessKey,omitempty"`        // 存储引擎的访问key
	AccessSecret string `protobuf:"bytes,8,opt,name=accessSecret,proto3" json:"accessSecret,omitempty"`  // 存储引擎的访问secret
	Url          string `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`                    // 存储引擎的外部访问地址
}

func (x *BucketUpdateRequest) Reset() {
	*x = BucketUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_bucket_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketUpdateRequest) ProtoMessage() {}

func (x *BucketUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_bucket_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketUpdateRequest.ProtoReflect.Descriptor instead.
func (*BucketUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_bucket_proto_rawDescGZIP(), []int{8}
}

func (x *BucketUpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *BucketUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketUpdateRequest) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *BucketUpdateRequest) GetEngine() Engine {
	if x != nil {
		return x.Engine
	}
	return Engine_ENGINE_INVALID
}

func (x *BucketUpdateRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BucketUpdateRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *BucketUpdateRequest) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *BucketUpdateRequest) GetAccessSecret() string {
	if x != nil {
		return x.AccessSecret
	}
	return ""
}

func (x *BucketUpdateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 重置存储桶的访问令牌
type BucketResetTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // uuid
}

func (x *BucketResetTokenRequest) Reset() {
	*x = BucketResetTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_bucket_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BucketResetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketResetTokenRequest) ProtoMessage() {}

func (x *BucketResetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_bucket_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketResetTokenRequest.ProtoReflect.Descriptor instead.
func (*BucketResetTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_bucket_proto_rawDescGZIP(), []int{9}
}

func (x *BucketResetTokenRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_proto_file_bucket_proto protoreflect.FileDescriptor

var file_proto_file_bucket_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xe8, 0x01, 0x0a, 0x11, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x61, 0x6b,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x06, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x52, 0x06, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x41, 0x0a,
	0x11, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x72, 0x0a, 0x12, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x25, 0x0a,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x22, 0x29, 0x0a, 0x13, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22,
	0x26, 0x0a, 0x10, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x5b, 0x0a, 0x11, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x22, 0x27, 0x0a, 0x11, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x69,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5c, 0x0a,
	0x12, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0xfe, 0x01, 0x0a, 0x13,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63,
	0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x06, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x52, 0x06, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x4b, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x2d, 0x0a, 0x17,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x32, 0xea, 0x02, 0x0a, 0x06,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x4d, 0x61, 0x6b, 0x65, 0x12, 0x12,
	0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x42,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x12, 0x14, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x03, 0x47, 0x65, 0x74,
	0x12, 0x11, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x04, 0x46, 0x69, 0x6e,
	0x64, 0x12, 0x12, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x69,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x06,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x42,
	0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38,
	0x0a, 0x0a, 0x52, 0x65, 0x73, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x2e, 0x42,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x3b, 0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_file_bucket_proto_rawDescOnce sync.Once
	file_proto_file_bucket_proto_rawDescData = file_proto_file_bucket_proto_rawDesc
)

func file_proto_file_bucket_proto_rawDescGZIP() []byte {
	file_proto_file_bucket_proto_rawDescOnce.Do(func() {
		file_proto_file_bucket_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_file_bucket_proto_rawDescData)
	})
	return file_proto_file_bucket_proto_rawDescData
}

var file_proto_file_bucket_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_file_bucket_proto_goTypes = []interface{}{
	(*BucketMakeRequest)(nil),       // 0: BucketMakeRequest
	(*BucketListRequest)(nil),       // 1: BucketListRequest
	(*BucketListResponse)(nil),      // 2: BucketListResponse
	(*BucketRemoveRequest)(nil),     // 3: BucketRemoveRequest
	(*BucketGetRequest)(nil),        // 4: BucketGetRequest
	(*BucketGetResponse)(nil),       // 5: BucketGetResponse
	(*BucketFindRequest)(nil),       // 6: BucketFindRequest
	(*BucketFindResponse)(nil),      // 7: BucketFindResponse
	(*BucketUpdateRequest)(nil),     // 8: BucketUpdateRequest
	(*BucketResetTokenRequest)(nil), // 9: BucketResetTokenRequest
	(Engine)(0),                     // 10: Engine
	(*Status)(nil),                  // 11: Status
	(*BucketEntity)(nil),            // 12: BucketEntity
	(*BlankResponse)(nil),           // 13: BlankResponse
}
var file_proto_file_bucket_proto_depIdxs = []int32{
	10, // 0: BucketMakeRequest.engine:type_name -> Engine
	11, // 1: BucketListResponse.status:type_name -> Status
	12, // 2: BucketListResponse.entity:type_name -> BucketEntity
	11, // 3: BucketGetResponse.status:type_name -> Status
	12, // 4: BucketGetResponse.entity:type_name -> BucketEntity
	11, // 5: BucketFindResponse.status:type_name -> Status
	12, // 6: BucketFindResponse.entity:type_name -> BucketEntity
	10, // 7: BucketUpdateRequest.engine:type_name -> Engine
	0,  // 8: Bucket.Make:input_type -> BucketMakeRequest
	1,  // 9: Bucket.List:input_type -> BucketListRequest
	3,  // 10: Bucket.Remove:input_type -> BucketRemoveRequest
	4,  // 11: Bucket.Get:input_type -> BucketGetRequest
	6,  // 12: Bucket.Find:input_type -> BucketFindRequest
	8,  // 13: Bucket.Update:input_type -> BucketUpdateRequest
	9,  // 14: Bucket.ResetToken:input_type -> BucketResetTokenRequest
	13, // 15: Bucket.Make:output_type -> BlankResponse
	2,  // 16: Bucket.List:output_type -> BucketListResponse
	13, // 17: Bucket.Remove:output_type -> BlankResponse
	5,  // 18: Bucket.Get:output_type -> BucketGetResponse
	7,  // 19: Bucket.Find:output_type -> BucketFindResponse
	13, // 20: Bucket.Update:output_type -> BlankResponse
	13, // 21: Bucket.ResetToken:output_type -> BlankResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_file_bucket_proto_init() }
func file_proto_file_bucket_proto_init() {
	if File_proto_file_bucket_proto != nil {
		return
	}
	file_proto_file_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_file_bucket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketMakeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_bucket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_bucket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_bucket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_bucket_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_bucket_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_bucket_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketFindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_bucket_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketFindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_bucket_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_bucket_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BucketResetTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_file_bucket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_file_bucket_proto_goTypes,
		DependencyIndexes: file_proto_file_bucket_proto_depIdxs,
		MessageInfos:      file_proto_file_bucket_proto_msgTypes,
	}.Build()
	File_proto_file_bucket_proto = out.File
	file_proto_file_bucket_proto_rawDesc = nil
	file_proto_file_bucket_proto_goTypes = nil
	file_proto_file_bucket_proto_depIdxs = nil
}
