// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/file/bucket.proto

package file

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Bucket service

func NewBucketEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Bucket service

type BucketService interface {
	// 创建一个存储桶
	Make(ctx context.Context, in *BucketMakeRequest, opts ...client.CallOption) (*UuidResponse, error)
	// 列举存储桶
	List(ctx context.Context, in *BucketListRequest, opts ...client.CallOption) (*BucketListResponse, error)
	// 删除一个存储桶
	Remove(ctx context.Context, in *BucketRemoveRequest, opts ...client.CallOption) (*UuidResponse, error)
	// 获取一个存储桶信息
	Get(ctx context.Context, in *BucketGetRequest, opts ...client.CallOption) (*BucketGetResponse, error)
	// 精确查找一个存储桶信息
	Find(ctx context.Context, in *BucketFindRequest, opts ...client.CallOption) (*BucketFindResponse, error)
	// 模糊查找一个存储桶信息
	Search(ctx context.Context, in *BucketSearchRequest, opts ...client.CallOption) (*BucketSearchResponse, error)
	// 更新一个存储桶
	Update(ctx context.Context, in *BucketUpdateRequest, opts ...client.CallOption) (*UuidResponse, error)
	// 重置一个存储桶的访问令牌
	ResetToken(ctx context.Context, in *BucketResetTokenRequest, opts ...client.CallOption) (*UuidResponse, error)
	// 生成清单
	GenerateManifest(ctx context.Context, in *BucketGenerateManifestRequest, opts ...client.CallOption) (*BucketGenerateManifestResponse, error)
}

type bucketService struct {
	c    client.Client
	name string
}

func NewBucketService(name string, c client.Client) BucketService {
	return &bucketService{
		c:    c,
		name: name,
	}
}

func (c *bucketService) Make(ctx context.Context, in *BucketMakeRequest, opts ...client.CallOption) (*UuidResponse, error) {
	req := c.c.NewRequest(c.name, "Bucket.Make", in)
	out := new(UuidResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketService) List(ctx context.Context, in *BucketListRequest, opts ...client.CallOption) (*BucketListResponse, error) {
	req := c.c.NewRequest(c.name, "Bucket.List", in)
	out := new(BucketListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketService) Remove(ctx context.Context, in *BucketRemoveRequest, opts ...client.CallOption) (*UuidResponse, error) {
	req := c.c.NewRequest(c.name, "Bucket.Remove", in)
	out := new(UuidResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketService) Get(ctx context.Context, in *BucketGetRequest, opts ...client.CallOption) (*BucketGetResponse, error) {
	req := c.c.NewRequest(c.name, "Bucket.Get", in)
	out := new(BucketGetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketService) Find(ctx context.Context, in *BucketFindRequest, opts ...client.CallOption) (*BucketFindResponse, error) {
	req := c.c.NewRequest(c.name, "Bucket.Find", in)
	out := new(BucketFindResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketService) Search(ctx context.Context, in *BucketSearchRequest, opts ...client.CallOption) (*BucketSearchResponse, error) {
	req := c.c.NewRequest(c.name, "Bucket.Search", in)
	out := new(BucketSearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketService) Update(ctx context.Context, in *BucketUpdateRequest, opts ...client.CallOption) (*UuidResponse, error) {
	req := c.c.NewRequest(c.name, "Bucket.Update", in)
	out := new(UuidResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketService) ResetToken(ctx context.Context, in *BucketResetTokenRequest, opts ...client.CallOption) (*UuidResponse, error) {
	req := c.c.NewRequest(c.name, "Bucket.ResetToken", in)
	out := new(UuidResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketService) GenerateManifest(ctx context.Context, in *BucketGenerateManifestRequest, opts ...client.CallOption) (*BucketGenerateManifestResponse, error) {
	req := c.c.NewRequest(c.name, "Bucket.GenerateManifest", in)
	out := new(BucketGenerateManifestResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bucket service

type BucketHandler interface {
	// 创建一个存储桶
	Make(context.Context, *BucketMakeRequest, *UuidResponse) error
	// 列举存储桶
	List(context.Context, *BucketListRequest, *BucketListResponse) error
	// 删除一个存储桶
	Remove(context.Context, *BucketRemoveRequest, *UuidResponse) error
	// 获取一个存储桶信息
	Get(context.Context, *BucketGetRequest, *BucketGetResponse) error
	// 精确查找一个存储桶信息
	Find(context.Context, *BucketFindRequest, *BucketFindResponse) error
	// 模糊查找一个存储桶信息
	Search(context.Context, *BucketSearchRequest, *BucketSearchResponse) error
	// 更新一个存储桶
	Update(context.Context, *BucketUpdateRequest, *UuidResponse) error
	// 重置一个存储桶的访问令牌
	ResetToken(context.Context, *BucketResetTokenRequest, *UuidResponse) error
	// 生成清单
	GenerateManifest(context.Context, *BucketGenerateManifestRequest, *BucketGenerateManifestResponse) error
}

func RegisterBucketHandler(s server.Server, hdlr BucketHandler, opts ...server.HandlerOption) error {
	type bucket interface {
		Make(ctx context.Context, in *BucketMakeRequest, out *UuidResponse) error
		List(ctx context.Context, in *BucketListRequest, out *BucketListResponse) error
		Remove(ctx context.Context, in *BucketRemoveRequest, out *UuidResponse) error
		Get(ctx context.Context, in *BucketGetRequest, out *BucketGetResponse) error
		Find(ctx context.Context, in *BucketFindRequest, out *BucketFindResponse) error
		Search(ctx context.Context, in *BucketSearchRequest, out *BucketSearchResponse) error
		Update(ctx context.Context, in *BucketUpdateRequest, out *UuidResponse) error
		ResetToken(ctx context.Context, in *BucketResetTokenRequest, out *UuidResponse) error
		GenerateManifest(ctx context.Context, in *BucketGenerateManifestRequest, out *BucketGenerateManifestResponse) error
	}
	type Bucket struct {
		bucket
	}
	h := &bucketHandler{hdlr}
	return s.Handle(s.NewHandler(&Bucket{h}, opts...))
}

type bucketHandler struct {
	BucketHandler
}

func (h *bucketHandler) Make(ctx context.Context, in *BucketMakeRequest, out *UuidResponse) error {
	return h.BucketHandler.Make(ctx, in, out)
}

func (h *bucketHandler) List(ctx context.Context, in *BucketListRequest, out *BucketListResponse) error {
	return h.BucketHandler.List(ctx, in, out)
}

func (h *bucketHandler) Remove(ctx context.Context, in *BucketRemoveRequest, out *UuidResponse) error {
	return h.BucketHandler.Remove(ctx, in, out)
}

func (h *bucketHandler) Get(ctx context.Context, in *BucketGetRequest, out *BucketGetResponse) error {
	return h.BucketHandler.Get(ctx, in, out)
}

func (h *bucketHandler) Find(ctx context.Context, in *BucketFindRequest, out *BucketFindResponse) error {
	return h.BucketHandler.Find(ctx, in, out)
}

func (h *bucketHandler) Search(ctx context.Context, in *BucketSearchRequest, out *BucketSearchResponse) error {
	return h.BucketHandler.Search(ctx, in, out)
}

func (h *bucketHandler) Update(ctx context.Context, in *BucketUpdateRequest, out *UuidResponse) error {
	return h.BucketHandler.Update(ctx, in, out)
}

func (h *bucketHandler) ResetToken(ctx context.Context, in *BucketResetTokenRequest, out *UuidResponse) error {
	return h.BucketHandler.ResetToken(ctx, in, out)
}

func (h *bucketHandler) GenerateManifest(ctx context.Context, in *BucketGenerateManifestRequest, out *BucketGenerateManifestResponse) error {
	return h.BucketHandler.GenerateManifest(ctx, in, out)
}
