// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: proto/file/object.proto

package file

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 准备对象元数据的请求
type ObjectPrepareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket   string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`      // 存储桶
	Uname    string `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`        // 存储引擎中的唯一名
	Size     uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`         // 对象大小
	Expiry   int64  `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`     //令牌有效期
	Override bool   `protobuf:"varint,5,opt,name=override,proto3" json:"override,omitempty"` // 覆盖已存在的对象
}

func (x *ObjectPrepareRequest) Reset() {
	*x = ObjectPrepareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectPrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectPrepareRequest) ProtoMessage() {}

func (x *ObjectPrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectPrepareRequest.ProtoReflect.Descriptor instead.
func (*ObjectPrepareRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectPrepareRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ObjectPrepareRequest) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *ObjectPrepareRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectPrepareRequest) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *ObjectPrepareRequest) GetOverride() bool {
	if x != nil {
		return x.Override
	}
	return false
}

// 准备对象的回复
type ObjectPrepareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`              // 状态
	Engine      Engine  `protobuf:"varint,2,opt,name=engine,proto3,enum=Engine" json:"engine,omitempty"` // 存储引擎
	Url         string  `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`                    // 访问地址
	AccessToken string  `protobuf:"bytes,4,opt,name=accessToken,proto3" json:"accessToken,omitempty"`    // 访问令牌
}

func (x *ObjectPrepareResponse) Reset() {
	*x = ObjectPrepareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectPrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectPrepareResponse) ProtoMessage() {}

func (x *ObjectPrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectPrepareResponse.ProtoReflect.Descriptor instead.
func (*ObjectPrepareResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectPrepareResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ObjectPrepareResponse) GetEngine() Engine {
	if x != nil {
		return x.Engine
	}
	return Engine_ENGINE_INVALID
}

func (x *ObjectPrepareResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ObjectPrepareResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// 写入对象元数据的请求
type ObjectFlushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"` // 存储桶(UUID)
	Uname  string `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`   // 存储引擎中的唯一名
	Path   string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`     // 对象存储的路径
	Md5    string `protobuf:"bytes,4,opt,name=md5,proto3" json:"md5,omitempty"`       // 对象的MD5值
}

func (x *ObjectFlushRequest) Reset() {
	*x = ObjectFlushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectFlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectFlushRequest) ProtoMessage() {}

func (x *ObjectFlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectFlushRequest.ProtoReflect.Descriptor instead.
func (*ObjectFlushRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectFlushRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ObjectFlushRequest) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *ObjectFlushRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ObjectFlushRequest) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

// 发布对象的请求
type ObjectPublishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid   string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`      // uuid
	Expiry uint64 `protobuf:"varint,2,opt,name=expiry,proto3" json:"expiry,omitempty"` // 有效期，单位秒
}

func (x *ObjectPublishRequest) Reset() {
	*x = ObjectPublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectPublishRequest) ProtoMessage() {}

func (x *ObjectPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectPublishRequest.ProtoReflect.Descriptor instead.
func (*ObjectPublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectPublishRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ObjectPublishRequest) GetExpiry() uint64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

// 发布对象的回复
type ObjectPublishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Url    string  `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`       // 访问地址
}

func (x *ObjectPublishResponse) Reset() {
	*x = ObjectPublishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectPublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectPublishResponse) ProtoMessage() {}

func (x *ObjectPublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectPublishResponse.ProtoReflect.Descriptor instead.
func (*ObjectPublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{4}
}

func (x *ObjectPublishResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ObjectPublishResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 预览对象的请求
type ObjectPreviewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid   string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`      // uuid
	Expiry int64  `protobuf:"varint,2,opt,name=expiry,proto3" json:"expiry,omitempty"` // 过期时间（单位：秒）
}

func (x *ObjectPreviewRequest) Reset() {
	*x = ObjectPreviewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectPreviewRequest) ProtoMessage() {}

func (x *ObjectPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectPreviewRequest.ProtoReflect.Descriptor instead.
func (*ObjectPreviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectPreviewRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ObjectPreviewRequest) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

// 预览对象的回复
type ObjectPreviewResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Url    string  `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`       // 访问地址
}

func (x *ObjectPreviewResponse) Reset() {
	*x = ObjectPreviewResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectPreviewResponse) ProtoMessage() {}

func (x *ObjectPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectPreviewResponse.ProtoReflect.Descriptor instead.
func (*ObjectPreviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectPreviewResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ObjectPreviewResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 撤回对象据的请求
type ObjectRetractRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // uuid
}

func (x *ObjectRetractRequest) Reset() {
	*x = ObjectRetractRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectRetractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRetractRequest) ProtoMessage() {}

func (x *ObjectRetractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRetractRequest.ProtoReflect.Descriptor instead.
func (*ObjectRetractRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectRetractRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 获取对象的请求
type ObjectGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // 唯一ID
}

func (x *ObjectGetRequest) Reset() {
	*x = ObjectGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectGetRequest) ProtoMessage() {}

func (x *ObjectGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectGetRequest.ProtoReflect.Descriptor instead.
func (*ObjectGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{8}
}

func (x *ObjectGetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 获取对象的回复
type ObjectGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Entity *ObjectEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"` // 实体
}

func (x *ObjectGetResponse) Reset() {
	*x = ObjectGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectGetResponse) ProtoMessage() {}

func (x *ObjectGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectGetResponse.ProtoReflect.Descriptor instead.
func (*ObjectGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{9}
}

func (x *ObjectGetResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ObjectGetResponse) GetEntity() *ObjectEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 查找对象的请求
type ObjectFindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket   string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`     // 存储桶
	Filepath string `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"` // 文件路径
}

func (x *ObjectFindRequest) Reset() {
	*x = ObjectFindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectFindRequest) ProtoMessage() {}

func (x *ObjectFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectFindRequest.ProtoReflect.Descriptor instead.
func (*ObjectFindRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{10}
}

func (x *ObjectFindRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ObjectFindRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

// 查找对象的回复
type ObjectFindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Entity *ObjectEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"` // 实体
}

func (x *ObjectFindResponse) Reset() {
	*x = ObjectFindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectFindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectFindResponse) ProtoMessage() {}

func (x *ObjectFindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectFindResponse.ProtoReflect.Descriptor instead.
func (*ObjectFindResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{11}
}

func (x *ObjectFindResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ObjectFindResponse) GetEntity() *ObjectEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 删除对象的请求
type ObjectRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // uuid
}

func (x *ObjectRemoveRequest) Reset() {
	*x = ObjectRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRemoveRequest) ProtoMessage() {}

func (x *ObjectRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRemoveRequest.ProtoReflect.Descriptor instead.
func (*ObjectRemoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{12}
}

func (x *ObjectRemoveRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 列举对象的请求
type ObjectListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移值
	Count  int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`   // 数量
	Bucket string `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`  // 储存桶(UUID)
}

func (x *ObjectListRequest) Reset() {
	*x = ObjectListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectListRequest) ProtoMessage() {}

func (x *ObjectListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectListRequest.ProtoReflect.Descriptor instead.
func (*ObjectListRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{13}
}

func (x *ObjectListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ObjectListRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ObjectListRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

// 列举对象的回复
type ObjectListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Total  uint64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`  // 总数
	Entity []*ObjectEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"` // 实体列表
}

func (x *ObjectListResponse) Reset() {
	*x = ObjectListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectListResponse) ProtoMessage() {}

func (x *ObjectListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectListResponse.ProtoReflect.Descriptor instead.
func (*ObjectListResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{14}
}

func (x *ObjectListResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ObjectListResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ObjectListResponse) GetEntity() []*ObjectEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 搜索对象的请求
type ObjectSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移值
	Count  int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`   // 数量
	Bucket string `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`  // 储存桶(UUID)
	Prefix string `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`  // 路径前缀
	Name   string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`      // 名称
}

func (x *ObjectSearchRequest) Reset() {
	*x = ObjectSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectSearchRequest) ProtoMessage() {}

func (x *ObjectSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectSearchRequest.ProtoReflect.Descriptor instead.
func (*ObjectSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{15}
}

func (x *ObjectSearchRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ObjectSearchRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ObjectSearchRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ObjectSearchRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ObjectSearchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 搜索对象的回复
type ObjectSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Total  uint64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`  // 总数
	Entity []*ObjectEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"` // 实体列表
}

func (x *ObjectSearchResponse) Reset() {
	*x = ObjectSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectSearchResponse) ProtoMessage() {}

func (x *ObjectSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectSearchResponse.ProtoReflect.Descriptor instead.
func (*ObjectSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{16}
}

func (x *ObjectSearchResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ObjectSearchResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ObjectSearchResponse) GetEntity() []*ObjectEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 将Base64编码的内容转换为对象的请求
type ObjectConvertFromBase64Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string          `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"` //  bucket's uuid
	Source []*Base64Source `protobuf:"bytes,2,rep,name=source,proto3" json:"source,omitempty"` // 源
}

func (x *ObjectConvertFromBase64Request) Reset() {
	*x = ObjectConvertFromBase64Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectConvertFromBase64Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectConvertFromBase64Request) ProtoMessage() {}

func (x *ObjectConvertFromBase64Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectConvertFromBase64Request.ProtoReflect.Descriptor instead.
func (*ObjectConvertFromBase64Request) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{17}
}

func (x *ObjectConvertFromBase64Request) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ObjectConvertFromBase64Request) GetSource() []*Base64Source {
	if x != nil {
		return x.Source
	}
	return nil
}

// 将Base64编码的内容转换为对象的回复
type ObjectConvertFromBase64Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // 状态
	Failure []string `protobuf:"bytes,2,rep,name=failure,proto3" json:"failure,omitempty"` // 转换失败的文件
}

func (x *ObjectConvertFromBase64Response) Reset() {
	*x = ObjectConvertFromBase64Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_object_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectConvertFromBase64Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectConvertFromBase64Response) ProtoMessage() {}

func (x *ObjectConvertFromBase64Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_object_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectConvertFromBase64Response.ProtoReflect.Descriptor instead.
func (*ObjectConvertFromBase64Response) Descriptor() ([]byte, []int) {
	return file_proto_file_object_proto_rawDescGZIP(), []int{18}
}

func (x *ObjectConvertFromBase64Response) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ObjectConvertFromBase64Response) GetFailure() []string {
	if x != nil {
		return x.Failure
	}
	return nil
}

var File_proto_file_object_proto protoreflect.FileDescriptor

var file_proto_file_object_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x14, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64,
	0x65, 0x22, 0x8d, 0x01, 0x0a, 0x15, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x06,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x45,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x06, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12,
	0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x68, 0x0a, 0x12, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x6c, 0x75, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x75, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x22, 0x42, 0x0a, 0x14, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x22,
	0x4a, 0x0a, 0x15, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x42, 0x0a, 0x14, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x22,
	0x4a, 0x0a, 0x15, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x2a, 0x0a, 0x14, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x10, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22,
	0x5b, 0x0a, 0x11, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x47, 0x0a, 0x11,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x70, 0x61, 0x74, 0x68, 0x22, 0x5c, 0x0a, 0x12, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x46,
	0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x06,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x22, 0x29, 0x0a, 0x13, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x59,
	0x0a, 0x11, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x72, 0x0a, 0x12, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x87, 0x01,
	0x0a, 0x13, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x74, 0x0a, 0x14, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x5f, 0x0a,
	0x1e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x46, 0x72,
	0x6f, 0x6d, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x5c,
	0x0a, 0x1f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x46,
	0x72, 0x6f, 0x6d, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x32, 0xf8, 0x04, 0x0a,
	0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x3a, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x12, 0x15, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x05, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x12, 0x13, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0d, 0x2e, 0x55, 0x75, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x2e, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x31, 0x0a, 0x04, 0x46, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x2e, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12,
	0x14, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x55, 0x75, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x06, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x12, 0x14, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x15, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a,
	0x0a, 0x07, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x15, 0x2e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x07, 0x52, 0x65,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x15, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x55,
	0x75, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a,
	0x11, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x61, 0x73, 0x65,
	0x36, 0x34, 0x12, 0x1f, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x66, 0x69, 0x6c, 0x65, 0x3b, 0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_file_object_proto_rawDescOnce sync.Once
	file_proto_file_object_proto_rawDescData = file_proto_file_object_proto_rawDesc
)

func file_proto_file_object_proto_rawDescGZIP() []byte {
	file_proto_file_object_proto_rawDescOnce.Do(func() {
		file_proto_file_object_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_file_object_proto_rawDescData)
	})
	return file_proto_file_object_proto_rawDescData
}

var file_proto_file_object_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_file_object_proto_goTypes = []interface{}{
	(*ObjectPrepareRequest)(nil),            // 0: ObjectPrepareRequest
	(*ObjectPrepareResponse)(nil),           // 1: ObjectPrepareResponse
	(*ObjectFlushRequest)(nil),              // 2: ObjectFlushRequest
	(*ObjectPublishRequest)(nil),            // 3: ObjectPublishRequest
	(*ObjectPublishResponse)(nil),           // 4: ObjectPublishResponse
	(*ObjectPreviewRequest)(nil),            // 5: ObjectPreviewRequest
	(*ObjectPreviewResponse)(nil),           // 6: ObjectPreviewResponse
	(*ObjectRetractRequest)(nil),            // 7: ObjectRetractRequest
	(*ObjectGetRequest)(nil),                // 8: ObjectGetRequest
	(*ObjectGetResponse)(nil),               // 9: ObjectGetResponse
	(*ObjectFindRequest)(nil),               // 10: ObjectFindRequest
	(*ObjectFindResponse)(nil),              // 11: ObjectFindResponse
	(*ObjectRemoveRequest)(nil),             // 12: ObjectRemoveRequest
	(*ObjectListRequest)(nil),               // 13: ObjectListRequest
	(*ObjectListResponse)(nil),              // 14: ObjectListResponse
	(*ObjectSearchRequest)(nil),             // 15: ObjectSearchRequest
	(*ObjectSearchResponse)(nil),            // 16: ObjectSearchResponse
	(*ObjectConvertFromBase64Request)(nil),  // 17: ObjectConvertFromBase64Request
	(*ObjectConvertFromBase64Response)(nil), // 18: ObjectConvertFromBase64Response
	(*Status)(nil),                          // 19: Status
	(Engine)(0),                             // 20: Engine
	(*ObjectEntity)(nil),                    // 21: ObjectEntity
	(*Base64Source)(nil),                    // 22: Base64Source
	(*UuidResponse)(nil),                    // 23: UuidResponse
}
var file_proto_file_object_proto_depIdxs = []int32{
	19, // 0: ObjectPrepareResponse.status:type_name -> Status
	20, // 1: ObjectPrepareResponse.engine:type_name -> Engine
	19, // 2: ObjectPublishResponse.status:type_name -> Status
	19, // 3: ObjectPreviewResponse.status:type_name -> Status
	19, // 4: ObjectGetResponse.status:type_name -> Status
	21, // 5: ObjectGetResponse.entity:type_name -> ObjectEntity
	19, // 6: ObjectFindResponse.status:type_name -> Status
	21, // 7: ObjectFindResponse.entity:type_name -> ObjectEntity
	19, // 8: ObjectListResponse.status:type_name -> Status
	21, // 9: ObjectListResponse.entity:type_name -> ObjectEntity
	19, // 10: ObjectSearchResponse.status:type_name -> Status
	21, // 11: ObjectSearchResponse.entity:type_name -> ObjectEntity
	22, // 12: ObjectConvertFromBase64Request.source:type_name -> Base64Source
	19, // 13: ObjectConvertFromBase64Response.status:type_name -> Status
	0,  // 14: Object.Prepare:input_type -> ObjectPrepareRequest
	2,  // 15: Object.Flush:input_type -> ObjectFlushRequest
	8,  // 16: Object.Get:input_type -> ObjectGetRequest
	10, // 17: Object.Find:input_type -> ObjectFindRequest
	12, // 18: Object.Remove:input_type -> ObjectRemoveRequest
	13, // 19: Object.List:input_type -> ObjectListRequest
	15, // 20: Object.Search:input_type -> ObjectSearchRequest
	3,  // 21: Object.Publish:input_type -> ObjectPublishRequest
	5,  // 22: Object.Preview:input_type -> ObjectPreviewRequest
	7,  // 23: Object.Retract:input_type -> ObjectRetractRequest
	17, // 24: Object.ConvertFromBase64:input_type -> ObjectConvertFromBase64Request
	1,  // 25: Object.Prepare:output_type -> ObjectPrepareResponse
	23, // 26: Object.Flush:output_type -> UuidResponse
	9,  // 27: Object.Get:output_type -> ObjectGetResponse
	11, // 28: Object.Find:output_type -> ObjectFindResponse
	23, // 29: Object.Remove:output_type -> UuidResponse
	14, // 30: Object.List:output_type -> ObjectListResponse
	16, // 31: Object.Search:output_type -> ObjectSearchResponse
	4,  // 32: Object.Publish:output_type -> ObjectPublishResponse
	6,  // 33: Object.Preview:output_type -> ObjectPreviewResponse
	23, // 34: Object.Retract:output_type -> UuidResponse
	18, // 35: Object.ConvertFromBase64:output_type -> ObjectConvertFromBase64Response
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_file_object_proto_init() }
func file_proto_file_object_proto_init() {
	if File_proto_file_object_proto != nil {
		return
	}
	file_proto_file_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_file_object_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectPrepareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectPrepareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectFlushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectPublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectPublishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectPreviewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectPreviewResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectRetractRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectFindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectFindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectConvertFromBase64Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_object_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectConvertFromBase64Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_file_object_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_file_object_proto_goTypes,
		DependencyIndexes: file_proto_file_object_proto_depIdxs,
		MessageInfos:      file_proto_file_object_proto_msgTypes,
	}.Build()
	File_proto_file_object_proto = out.File
	file_proto_file_object_proto_rawDesc = nil
	file_proto_file_object_proto_goTypes = nil
	file_proto_file_object_proto_depIdxs = nil
}
