// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/file/object.proto

package file

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 打开对象的存储通道的请求
type ObjectOpenRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Md5                  string   `protobuf:"bytes,2,opt,name=md5,proto3" json:"md5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectOpenRequest) Reset()         { *m = ObjectOpenRequest{} }
func (m *ObjectOpenRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectOpenRequest) ProtoMessage()    {}
func (*ObjectOpenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{0}
}

func (m *ObjectOpenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectOpenRequest.Unmarshal(m, b)
}
func (m *ObjectOpenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectOpenRequest.Marshal(b, m, deterministic)
}
func (m *ObjectOpenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectOpenRequest.Merge(m, src)
}
func (m *ObjectOpenRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectOpenRequest.Size(m)
}
func (m *ObjectOpenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectOpenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectOpenRequest proto.InternalMessageInfo

func (m *ObjectOpenRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ObjectOpenRequest) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

// 打开对象的存储通道的回复
type ObjectOpenResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectOpenResponse) Reset()         { *m = ObjectOpenResponse{} }
func (m *ObjectOpenResponse) String() string { return proto.CompactTextString(m) }
func (*ObjectOpenResponse) ProtoMessage()    {}
func (*ObjectOpenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{1}
}

func (m *ObjectOpenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectOpenResponse.Unmarshal(m, b)
}
func (m *ObjectOpenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectOpenResponse.Marshal(b, m, deterministic)
}
func (m *ObjectOpenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectOpenResponse.Merge(m, src)
}
func (m *ObjectOpenResponse) XXX_Size() int {
	return xxx_messageInfo_ObjectOpenResponse.Size(m)
}
func (m *ObjectOpenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectOpenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectOpenResponse proto.InternalMessageInfo

func (m *ObjectOpenResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ObjectOpenResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ObjectOpenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

// 上传对象的请求
type ObjectUploadRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Filepath             string   `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Overwrite            bool     `protobuf:"varint,4,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectUploadRequest) Reset()         { *m = ObjectUploadRequest{} }
func (m *ObjectUploadRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectUploadRequest) ProtoMessage()    {}
func (*ObjectUploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{2}
}

func (m *ObjectUploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectUploadRequest.Unmarshal(m, b)
}
func (m *ObjectUploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectUploadRequest.Marshal(b, m, deterministic)
}
func (m *ObjectUploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectUploadRequest.Merge(m, src)
}
func (m *ObjectUploadRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectUploadRequest.Size(m)
}
func (m *ObjectUploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectUploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectUploadRequest proto.InternalMessageInfo

func (m *ObjectUploadRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ObjectUploadRequest) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *ObjectUploadRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ObjectUploadRequest) GetOverwrite() bool {
	if m != nil {
		return m.Overwrite
	}
	return false
}

// 下载对象的请求
type ObjectDownloadRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Filepath             string   `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectDownloadRequest) Reset()         { *m = ObjectDownloadRequest{} }
func (m *ObjectDownloadRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectDownloadRequest) ProtoMessage()    {}
func (*ObjectDownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{3}
}

func (m *ObjectDownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectDownloadRequest.Unmarshal(m, b)
}
func (m *ObjectDownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectDownloadRequest.Marshal(b, m, deterministic)
}
func (m *ObjectDownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectDownloadRequest.Merge(m, src)
}
func (m *ObjectDownloadRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectDownloadRequest.Size(m)
}
func (m *ObjectDownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectDownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectDownloadRequest proto.InternalMessageInfo

func (m *ObjectDownloadRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ObjectDownloadRequest) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

// 下载对象的回复
type ObjectDownloadResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectDownloadResponse) Reset()         { *m = ObjectDownloadResponse{} }
func (m *ObjectDownloadResponse) String() string { return proto.CompactTextString(m) }
func (*ObjectDownloadResponse) ProtoMessage()    {}
func (*ObjectDownloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{4}
}

func (m *ObjectDownloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectDownloadResponse.Unmarshal(m, b)
}
func (m *ObjectDownloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectDownloadResponse.Marshal(b, m, deterministic)
}
func (m *ObjectDownloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectDownloadResponse.Merge(m, src)
}
func (m *ObjectDownloadResponse) XXX_Size() int {
	return xxx_messageInfo_ObjectDownloadResponse.Size(m)
}
func (m *ObjectDownloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectDownloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectDownloadResponse proto.InternalMessageInfo

func (m *ObjectDownloadResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ObjectDownloadResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 链接对象的请求
type ObjectLinkRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Filepath             string   `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Overwrite            bool     `protobuf:"varint,4,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectLinkRequest) Reset()         { *m = ObjectLinkRequest{} }
func (m *ObjectLinkRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectLinkRequest) ProtoMessage()    {}
func (*ObjectLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{5}
}

func (m *ObjectLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectLinkRequest.Unmarshal(m, b)
}
func (m *ObjectLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectLinkRequest.Marshal(b, m, deterministic)
}
func (m *ObjectLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectLinkRequest.Merge(m, src)
}
func (m *ObjectLinkRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectLinkRequest.Size(m)
}
func (m *ObjectLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectLinkRequest proto.InternalMessageInfo

func (m *ObjectLinkRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ObjectLinkRequest) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *ObjectLinkRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ObjectLinkRequest) GetOverwrite() bool {
	if m != nil {
		return m.Overwrite
	}
	return false
}

// 获取对象的请求
type ObjectGetRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Filepath             string   `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectGetRequest) Reset()         { *m = ObjectGetRequest{} }
func (m *ObjectGetRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectGetRequest) ProtoMessage()    {}
func (*ObjectGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{6}
}

func (m *ObjectGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectGetRequest.Unmarshal(m, b)
}
func (m *ObjectGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectGetRequest.Marshal(b, m, deterministic)
}
func (m *ObjectGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectGetRequest.Merge(m, src)
}
func (m *ObjectGetRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectGetRequest.Size(m)
}
func (m *ObjectGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectGetRequest proto.InternalMessageInfo

func (m *ObjectGetRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ObjectGetRequest) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

// 获取对象的回复
type ObjectGetResponse struct {
	Status               *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Entity               *ObjectEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ObjectGetResponse) Reset()         { *m = ObjectGetResponse{} }
func (m *ObjectGetResponse) String() string { return proto.CompactTextString(m) }
func (*ObjectGetResponse) ProtoMessage()    {}
func (*ObjectGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{7}
}

func (m *ObjectGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectGetResponse.Unmarshal(m, b)
}
func (m *ObjectGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectGetResponse.Marshal(b, m, deterministic)
}
func (m *ObjectGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectGetResponse.Merge(m, src)
}
func (m *ObjectGetResponse) XXX_Size() int {
	return xxx_messageInfo_ObjectGetResponse.Size(m)
}
func (m *ObjectGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectGetResponse proto.InternalMessageInfo

func (m *ObjectGetResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ObjectGetResponse) GetEntity() *ObjectEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

// 删除对象的请求
type ObjectRemoveRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Filepath             string   `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectRemoveRequest) Reset()         { *m = ObjectRemoveRequest{} }
func (m *ObjectRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectRemoveRequest) ProtoMessage()    {}
func (*ObjectRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{8}
}

func (m *ObjectRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectRemoveRequest.Unmarshal(m, b)
}
func (m *ObjectRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectRemoveRequest.Marshal(b, m, deterministic)
}
func (m *ObjectRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectRemoveRequest.Merge(m, src)
}
func (m *ObjectRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectRemoveRequest.Size(m)
}
func (m *ObjectRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectRemoveRequest proto.InternalMessageInfo

func (m *ObjectRemoveRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ObjectRemoveRequest) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

// 列举对象的请求
type ObjectListRequest struct {
	Offset               uint64   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectListRequest) Reset()         { *m = ObjectListRequest{} }
func (m *ObjectListRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectListRequest) ProtoMessage()    {}
func (*ObjectListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{9}
}

func (m *ObjectListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectListRequest.Unmarshal(m, b)
}
func (m *ObjectListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectListRequest.Marshal(b, m, deterministic)
}
func (m *ObjectListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectListRequest.Merge(m, src)
}
func (m *ObjectListRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectListRequest.Size(m)
}
func (m *ObjectListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectListRequest proto.InternalMessageInfo

func (m *ObjectListRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ObjectListRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 列举对象的回复
type ObjectListResponse struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []*ObjectEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ObjectListResponse) Reset()         { *m = ObjectListResponse{} }
func (m *ObjectListResponse) String() string { return proto.CompactTextString(m) }
func (*ObjectListResponse) ProtoMessage()    {}
func (*ObjectListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{10}
}

func (m *ObjectListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectListResponse.Unmarshal(m, b)
}
func (m *ObjectListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectListResponse.Marshal(b, m, deterministic)
}
func (m *ObjectListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectListResponse.Merge(m, src)
}
func (m *ObjectListResponse) XXX_Size() int {
	return xxx_messageInfo_ObjectListResponse.Size(m)
}
func (m *ObjectListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectListResponse proto.InternalMessageInfo

func (m *ObjectListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ObjectListResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ObjectListResponse) GetEntity() []*ObjectEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*ObjectOpenRequest)(nil), "file.ObjectOpenRequest")
	proto.RegisterType((*ObjectOpenResponse)(nil), "file.ObjectOpenResponse")
	proto.RegisterType((*ObjectUploadRequest)(nil), "file.ObjectUploadRequest")
	proto.RegisterType((*ObjectDownloadRequest)(nil), "file.ObjectDownloadRequest")
	proto.RegisterType((*ObjectDownloadResponse)(nil), "file.ObjectDownloadResponse")
	proto.RegisterType((*ObjectLinkRequest)(nil), "file.ObjectLinkRequest")
	proto.RegisterType((*ObjectGetRequest)(nil), "file.ObjectGetRequest")
	proto.RegisterType((*ObjectGetResponse)(nil), "file.ObjectGetResponse")
	proto.RegisterType((*ObjectRemoveRequest)(nil), "file.ObjectRemoveRequest")
	proto.RegisterType((*ObjectListRequest)(nil), "file.ObjectListRequest")
	proto.RegisterType((*ObjectListResponse)(nil), "file.ObjectListResponse")
}

func init() {
	proto.RegisterFile("proto/file/object.proto", fileDescriptor_5044922ea3425f24)
}

var fileDescriptor_5044922ea3425f24 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x6e, 0x6a, 0xd7, 0xb4, 0x93, 0x1e, 0xc2, 0xb4, 0x24, 0xc6, 0xf4, 0x10, 0xad, 0x38, 0x44,
	0x1c, 0x52, 0x14, 0x04, 0x42, 0x14, 0x0e, 0x20, 0xa0, 0xaa, 0x40, 0xaa, 0xb4, 0xc0, 0x03, 0x6c,
	0xec, 0x8d, 0x1a, 0xe2, 0x7a, 0x8d, 0x77, 0x9d, 0x08, 0xc1, 0x8b, 0xf1, 0x76, 0xc8, 0xbb, 0xde,
	0x64, 0x9d, 0x52, 0xaa, 0x28, 0xb7, 0x9d, 0xbf, 0x6f, 0xbe, 0xf9, 0x3c, 0x63, 0xe8, 0xe5, 0x85,
	0x50, 0xe2, 0x74, 0x32, 0x4d, 0xf9, 0xa9, 0x18, 0x7f, 0xe7, 0xb1, 0x1a, 0x6a, 0x0f, 0xfa, 0x95,
	0x2b, 0x72, 0xc3, 0xf2, 0x8a, 0x15, 0x3c, 0x31, 0x61, 0xf2, 0x06, 0xee, 0x5f, 0xea, 0xf4, 0xcb,
	0x9c, 0x67, 0x94, 0xff, 0x28, 0xb9, 0x54, 0xd8, 0x85, 0x60, 0x5c, 0xc6, 0x33, 0xae, 0xc2, 0x56,
	0xbf, 0x35, 0x38, 0xa0, 0xb5, 0x85, 0x1d, 0xf0, 0xae, 0x93, 0xe7, 0xe1, 0xae, 0x76, 0x56, 0x4f,
	0x32, 0x07, 0x74, 0xcb, 0x65, 0x2e, 0x32, 0xc9, 0xf1, 0x31, 0x04, 0x52, 0x31, 0x55, 0x4a, 0x5d,
	0xdf, 0x1e, 0x1d, 0x0e, 0xab, 0xc6, 0xc3, 0x2f, 0xda, 0x47, 0xeb, 0x18, 0x86, 0x70, 0x8f, 0x25,
	0x49, 0xc1, 0xa5, 0xac, 0x11, 0xad, 0x89, 0x7d, 0x68, 0xb3, 0x38, 0xe6, 0x52, 0x7e, 0x15, 0x33,
	0x9e, 0x85, 0x9e, 0x8e, 0xba, 0x2e, 0xf2, 0x0b, 0x8e, 0x4c, 0xdf, 0x6f, 0x79, 0x2a, 0x58, 0x72,
	0x17, 0xf1, 0x08, 0xf6, 0x2b, 0x06, 0x39, 0x53, 0x57, 0x75, 0xaf, 0xa5, 0x8d, 0x08, 0x7e, 0xc2,
	0x14, 0xd3, 0x5d, 0x0e, 0xa9, 0x7e, 0xe3, 0x09, 0x1c, 0x88, 0x39, 0x2f, 0x16, 0xc5, 0x54, 0xf1,
	0xd0, 0xef, 0xb7, 0x06, 0xfb, 0x74, 0xe5, 0x20, 0x9f, 0xe0, 0x81, 0x69, 0xfe, 0x5e, 0x2c, 0xb2,
	0x2d, 0xdb, 0x13, 0x0a, 0xdd, 0x75, 0xb0, 0x8d, 0x54, 0xb4, 0xf4, 0x77, 0x57, 0xf4, 0xc9, 0xc2,
	0x7e, 0xd4, 0xcf, 0xd3, 0x6c, 0xb6, 0x8d, 0x36, 0x1d, 0xf0, 0xca, 0x22, 0xad, 0x3f, 0x40, 0xf5,
	0xbc, 0x43, 0x99, 0x8f, 0xd0, 0x31, 0x8d, 0xcf, 0xb9, 0xda, 0x46, 0x14, 0x6e, 0x07, 0xd0, 0x38,
	0x1b, 0xe9, 0xf1, 0x04, 0x02, 0x9e, 0xa9, 0xa9, 0xfa, 0xa9, 0x41, 0xdb, 0x23, 0x34, 0x59, 0x06,
	0xee, 0x83, 0x8e, 0xd0, 0x3a, 0x83, 0x5c, 0xd8, 0x2d, 0xa2, 0xfc, 0x5a, 0xcc, 0xf9, 0x36, 0x8c,
	0xdf, 0xae, 0x24, 0x97, 0xee, 0xe8, 0x62, 0x32, 0x91, 0x35, 0x90, 0x4f, 0x6b, 0x0b, 0x8f, 0x61,
	0x2f, 0x16, 0x65, 0xa6, 0x34, 0x8a, 0x4f, 0x8d, 0x41, 0x7e, 0xdb, 0x5b, 0x32, 0x10, 0x1b, 0x4d,
	0x7d, 0x0c, 0x7b, 0x4a, 0x28, 0x96, 0x5a, 0x44, 0x6d, 0x38, 0x5a, 0x78, 0x7d, 0xef, 0xff, 0x5a,
	0x8c, 0xfe, 0x78, 0x10, 0x98, 0x00, 0x9e, 0x81, 0x5f, 0x9d, 0x33, 0xf6, 0xdc, 0x74, 0xe7, 0xff,
	0x10, 0x85, 0x37, 0x03, 0x86, 0x2d, 0xd9, 0xc1, 0xd7, 0x10, 0x98, 0x9b, 0xc4, 0x87, 0x6e, 0x56,
	0xe3, 0x4e, 0xa3, 0x23, 0x13, 0x7a, 0x97, 0xb2, 0x6a, 0x3f, 0x6d, 0xed, 0xa0, 0x85, 0x17, 0xb0,
	0x6f, 0xef, 0x00, 0x1f, 0xb9, 0xf5, 0x6b, 0xa7, 0x16, 0x9d, 0xfc, 0x3b, 0x68, 0xa1, 0x9e, 0xb6,
	0xf0, 0x05, 0xf8, 0xd5, 0xfa, 0x37, 0xa7, 0x70, 0x0e, 0xe2, 0x16, 0x12, 0xf8, 0x12, 0xbc, 0x73,
	0xae, 0xb0, 0xeb, 0x96, 0xad, 0xd6, 0x39, 0xea, 0xdd, 0xf0, 0x2f, 0x2b, 0x5f, 0x41, 0x60, 0x16,
	0xa9, 0x39, 0x7a, 0x63, 0xb9, 0x6e, 0xeb, 0x7a, 0x56, 0xb1, 0x95, 0x6a, 0x9d, 0xed, 0x72, 0x97,
	0x9a, 0x9a, 0xbb, 0x1b, 0x42, 0x76, 0xc6, 0x81, 0xfe, 0x97, 0x3f, 0xfb, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0xdb, 0xe8, 0xa8, 0x61, 0x05, 0x06, 0x00, 0x00,
}
