// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/file/object.proto

package file

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 准备对象元数据的请求
type ObjectPrepareRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Uname                string   `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	Size                 uint64   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectPrepareRequest) Reset()         { *m = ObjectPrepareRequest{} }
func (m *ObjectPrepareRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectPrepareRequest) ProtoMessage()    {}
func (*ObjectPrepareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{0}
}

func (m *ObjectPrepareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectPrepareRequest.Unmarshal(m, b)
}
func (m *ObjectPrepareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectPrepareRequest.Marshal(b, m, deterministic)
}
func (m *ObjectPrepareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectPrepareRequest.Merge(m, src)
}
func (m *ObjectPrepareRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectPrepareRequest.Size(m)
}
func (m *ObjectPrepareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectPrepareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectPrepareRequest proto.InternalMessageInfo

func (m *ObjectPrepareRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ObjectPrepareRequest) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *ObjectPrepareRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

// 准备对象的回复
type ObjectPrepareResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Engine               Engine   `protobuf:"varint,2,opt,name=engine,proto3,enum=file.Engine" json:"engine,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	AccessToken          string   `protobuf:"bytes,4,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectPrepareResponse) Reset()         { *m = ObjectPrepareResponse{} }
func (m *ObjectPrepareResponse) String() string { return proto.CompactTextString(m) }
func (*ObjectPrepareResponse) ProtoMessage()    {}
func (*ObjectPrepareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{1}
}

func (m *ObjectPrepareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectPrepareResponse.Unmarshal(m, b)
}
func (m *ObjectPrepareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectPrepareResponse.Marshal(b, m, deterministic)
}
func (m *ObjectPrepareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectPrepareResponse.Merge(m, src)
}
func (m *ObjectPrepareResponse) XXX_Size() int {
	return xxx_messageInfo_ObjectPrepareResponse.Size(m)
}
func (m *ObjectPrepareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectPrepareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectPrepareResponse proto.InternalMessageInfo

func (m *ObjectPrepareResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ObjectPrepareResponse) GetEngine() Engine {
	if m != nil {
		return m.Engine
	}
	return Engine_ENGINE_INVALID
}

func (m *ObjectPrepareResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ObjectPrepareResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

// 写入对象元数据的请求
type ObjectFlushRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Uname                string   `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectFlushRequest) Reset()         { *m = ObjectFlushRequest{} }
func (m *ObjectFlushRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectFlushRequest) ProtoMessage()    {}
func (*ObjectFlushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{2}
}

func (m *ObjectFlushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectFlushRequest.Unmarshal(m, b)
}
func (m *ObjectFlushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectFlushRequest.Marshal(b, m, deterministic)
}
func (m *ObjectFlushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectFlushRequest.Merge(m, src)
}
func (m *ObjectFlushRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectFlushRequest.Size(m)
}
func (m *ObjectFlushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectFlushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectFlushRequest proto.InternalMessageInfo

func (m *ObjectFlushRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ObjectFlushRequest) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *ObjectFlushRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// 获取对象的请求
type ObjectGetRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectGetRequest) Reset()         { *m = ObjectGetRequest{} }
func (m *ObjectGetRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectGetRequest) ProtoMessage()    {}
func (*ObjectGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{3}
}

func (m *ObjectGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectGetRequest.Unmarshal(m, b)
}
func (m *ObjectGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectGetRequest.Marshal(b, m, deterministic)
}
func (m *ObjectGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectGetRequest.Merge(m, src)
}
func (m *ObjectGetRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectGetRequest.Size(m)
}
func (m *ObjectGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectGetRequest proto.InternalMessageInfo

func (m *ObjectGetRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

// 获取对象的回复
type ObjectGetResponse struct {
	Status               *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Entity               *ObjectEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ObjectGetResponse) Reset()         { *m = ObjectGetResponse{} }
func (m *ObjectGetResponse) String() string { return proto.CompactTextString(m) }
func (*ObjectGetResponse) ProtoMessage()    {}
func (*ObjectGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{4}
}

func (m *ObjectGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectGetResponse.Unmarshal(m, b)
}
func (m *ObjectGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectGetResponse.Marshal(b, m, deterministic)
}
func (m *ObjectGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectGetResponse.Merge(m, src)
}
func (m *ObjectGetResponse) XXX_Size() int {
	return xxx_messageInfo_ObjectGetResponse.Size(m)
}
func (m *ObjectGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectGetResponse proto.InternalMessageInfo

func (m *ObjectGetResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ObjectGetResponse) GetEntity() *ObjectEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

// 删除对象的请求
type ObjectRemoveRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Filepath             string   `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectRemoveRequest) Reset()         { *m = ObjectRemoveRequest{} }
func (m *ObjectRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectRemoveRequest) ProtoMessage()    {}
func (*ObjectRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{5}
}

func (m *ObjectRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectRemoveRequest.Unmarshal(m, b)
}
func (m *ObjectRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectRemoveRequest.Marshal(b, m, deterministic)
}
func (m *ObjectRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectRemoveRequest.Merge(m, src)
}
func (m *ObjectRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectRemoveRequest.Size(m)
}
func (m *ObjectRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectRemoveRequest proto.InternalMessageInfo

func (m *ObjectRemoveRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ObjectRemoveRequest) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

// 列举对象的请求
type ObjectListRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Bucket               string   `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectListRequest) Reset()         { *m = ObjectListRequest{} }
func (m *ObjectListRequest) String() string { return proto.CompactTextString(m) }
func (*ObjectListRequest) ProtoMessage()    {}
func (*ObjectListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{6}
}

func (m *ObjectListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectListRequest.Unmarshal(m, b)
}
func (m *ObjectListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectListRequest.Marshal(b, m, deterministic)
}
func (m *ObjectListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectListRequest.Merge(m, src)
}
func (m *ObjectListRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectListRequest.Size(m)
}
func (m *ObjectListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectListRequest proto.InternalMessageInfo

func (m *ObjectListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ObjectListRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ObjectListRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

// 列举对象的回复
type ObjectListResponse struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []*ObjectEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ObjectListResponse) Reset()         { *m = ObjectListResponse{} }
func (m *ObjectListResponse) String() string { return proto.CompactTextString(m) }
func (*ObjectListResponse) ProtoMessage()    {}
func (*ObjectListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5044922ea3425f24, []int{7}
}

func (m *ObjectListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectListResponse.Unmarshal(m, b)
}
func (m *ObjectListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectListResponse.Marshal(b, m, deterministic)
}
func (m *ObjectListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectListResponse.Merge(m, src)
}
func (m *ObjectListResponse) XXX_Size() int {
	return xxx_messageInfo_ObjectListResponse.Size(m)
}
func (m *ObjectListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectListResponse proto.InternalMessageInfo

func (m *ObjectListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ObjectListResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ObjectListResponse) GetEntity() []*ObjectEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*ObjectPrepareRequest)(nil), "file.ObjectPrepareRequest")
	proto.RegisterType((*ObjectPrepareResponse)(nil), "file.ObjectPrepareResponse")
	proto.RegisterType((*ObjectFlushRequest)(nil), "file.ObjectFlushRequest")
	proto.RegisterType((*ObjectGetRequest)(nil), "file.ObjectGetRequest")
	proto.RegisterType((*ObjectGetResponse)(nil), "file.ObjectGetResponse")
	proto.RegisterType((*ObjectRemoveRequest)(nil), "file.ObjectRemoveRequest")
	proto.RegisterType((*ObjectListRequest)(nil), "file.ObjectListRequest")
	proto.RegisterType((*ObjectListResponse)(nil), "file.ObjectListResponse")
}

func init() {
	proto.RegisterFile("proto/file/object.proto", fileDescriptor_5044922ea3425f24)
}

var fileDescriptor_5044922ea3425f24 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x25, 0xb5, 0xe3, 0xd2, 0x09, 0x42, 0x30, 0x0d, 0xad, 0x31, 0x97, 0x68, 0x85, 0x50, 0xc5,
	0x21, 0x95, 0xc2, 0x05, 0xc1, 0x0d, 0x51, 0x2a, 0x24, 0x24, 0xd0, 0x82, 0x10, 0x1c, 0x37, 0xce,
	0x84, 0x98, 0xa4, 0xde, 0xe0, 0xdd, 0x45, 0x02, 0xf1, 0x5f, 0xf8, 0x21, 0xfc, 0x39, 0xe4, 0xd9,
	0x75, 0xd9, 0x50, 0x3e, 0x94, 0xde, 0x76, 0xde, 0x7b, 0xf3, 0x66, 0x76, 0x66, 0x6d, 0x38, 0x5c,
	0x37, 0xda, 0xea, 0xe3, 0x79, 0xb5, 0xa2, 0x63, 0x3d, 0xfd, 0x48, 0xa5, 0x1d, 0x33, 0x82, 0x69,
	0x0b, 0x15, 0x31, 0x6d, 0x16, 0xaa, 0xa1, 0x99, 0xa7, 0xc5, 0x3b, 0x18, 0xbe, 0x64, 0xf9, 0xab,
	0x86, 0xd6, 0xaa, 0x21, 0x49, 0x9f, 0x1c, 0x19, 0x8b, 0x07, 0x90, 0x4d, 0x5d, 0xb9, 0x24, 0x9b,
	0xf7, 0x46, 0xbd, 0xa3, 0x3d, 0x19, 0x22, 0x1c, 0x42, 0xdf, 0xd5, 0xea, 0x8c, 0xf2, 0x1d, 0x86,
	0x7d, 0x80, 0x08, 0xa9, 0xa9, 0xbe, 0x52, 0x9e, 0x8c, 0x7a, 0x47, 0xa9, 0xe4, 0xb3, 0xf8, 0xde,
	0x83, 0x5b, 0xbf, 0x59, 0x9b, 0xb5, 0xae, 0x0d, 0xe1, 0x5d, 0xc8, 0x8c, 0x55, 0xd6, 0x19, 0xf6,
	0x1e, 0x4c, 0xae, 0x8d, 0xdb, 0xbe, 0xc6, 0xaf, 0x19, 0x93, 0x81, 0x6b, 0x55, 0x54, 0x7f, 0xa8,
	0x6a, 0x5f, 0xea, 0x7a, 0xa7, 0x3a, 0x61, 0x4c, 0x06, 0x0e, 0x73, 0xd8, 0x55, 0xb3, 0x59, 0x43,
	0xc6, 0x70, 0xf1, 0x3d, 0xd9, 0x85, 0x38, 0x82, 0x81, 0x2a, 0x4b, 0x32, 0xe6, 0x8d, 0x5e, 0x52,
	0x9d, 0xa7, 0xcc, 0xc6, 0x90, 0x78, 0x0b, 0xe8, 0x1b, 0x7c, 0xb6, 0x72, 0x66, 0x71, 0xe9, 0x9b,
	0xaf, 0x95, 0x5d, 0x84, 0xe2, 0x7c, 0x16, 0xf7, 0xe0, 0x86, 0xf7, 0x3d, 0x25, 0xdb, 0xb9, 0x22,
	0xa4, 0xce, 0x55, 0xb3, 0xe0, 0xc9, 0x67, 0x41, 0x70, 0x33, 0xd2, 0x6d, 0x35, 0x9c, 0xfb, 0xed,
	0x70, 0x6c, 0x65, 0xbf, 0x70, 0x37, 0x83, 0x09, 0x7a, 0x95, 0xb7, 0x3b, 0x61, 0x46, 0x06, 0x85,
	0x78, 0x0e, 0xfb, 0x1e, 0x97, 0x74, 0xa6, 0x3f, 0xff, 0x77, 0xc3, 0x05, 0x5c, 0x6d, 0xbd, 0xf8,
	0x56, 0xfe, 0xaa, 0xe7, 0xb1, 0x78, 0xdf, 0x75, 0xfc, 0xa2, 0x32, 0x36, 0x32, 0xd2, 0xf3, 0xb9,
	0x09, 0x46, 0x89, 0x0c, 0x51, 0x3b, 0xb0, 0x52, 0xbb, 0xda, 0xb2, 0x4b, 0x22, 0x7d, 0x10, 0x95,
	0x4d, 0xe2, 0xb2, 0xe2, 0x5b, 0xb7, 0x0c, 0x6f, 0xbd, 0xd5, 0x34, 0x86, 0xd0, 0xb7, 0xda, 0xaa,
	0x15, 0x57, 0x4a, 0xa5, 0x0f, 0xa2, 0x19, 0x25, 0xa3, 0xe4, 0xdf, 0x33, 0x9a, 0xfc, 0xd8, 0x81,
	0xcc, 0x13, 0xf8, 0x14, 0x76, 0xc3, 0x83, 0xc5, 0x22, 0xce, 0xd8, 0xfc, 0x40, 0x8a, 0x3b, 0x7f,
	0xe4, 0x7c, 0xdb, 0xe2, 0x0a, 0x3e, 0x84, 0x3e, 0xbf, 0x2a, 0xcc, 0x63, 0x5d, 0xfc, 0xd0, 0x8a,
	0x7d, 0xcf, 0x3c, 0x59, 0xa9, 0x7a, 0xb9, 0x91, 0x99, 0x9c, 0x92, 0xc5, 0x83, 0x38, 0xef, 0xd7,
	0x43, 0x2a, 0x0e, 0x2f, 0xe0, 0xe7, 0x99, 0x8f, 0x20, 0xf3, 0x2b, 0xc6, 0xdb, 0xb1, 0x68, 0x63,
	0xed, 0x7f, 0xab, 0xfa, 0x18, 0xd2, 0x76, 0xf0, 0xb8, 0x61, 0x1f, 0x6d, 0xb9, 0xc8, 0x2f, 0x12,
	0x5d, 0xf2, 0x34, 0xe3, 0x7f, 0xc9, 0x83, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x39, 0xd3, 0xaa,
	0x54, 0x85, 0x04, 0x00, 0x00,
}
