// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/file/shared.proto

package file

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 存储引擎
type Engine int32

const (
	Engine_ENGINE_INVALID Engine = 0
	Engine_ENGINE_MINIO   Engine = 1
	Engine_ENGINE_QINIU   Engine = 2
	Engine_ENGINE_CUSTOM  Engine = 100
)

var Engine_name = map[int32]string{
	0:   "ENGINE_INVALID",
	1:   "ENGINE_MINIO",
	2:   "ENGINE_QINIU",
	100: "ENGINE_CUSTOM",
}

var Engine_value = map[string]int32{
	"ENGINE_INVALID": 0,
	"ENGINE_MINIO":   1,
	"ENGINE_QINIU":   2,
	"ENGINE_CUSTOM":  100,
}

func (x Engine) String() string {
	return proto.EnumName(Engine_name, int32(x))
}

func (Engine) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_64925fc78a369f37, []int{0}
}

// 状态
type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_64925fc78a369f37, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 空白请求
type BlankRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlankRequest) Reset()         { *m = BlankRequest{} }
func (m *BlankRequest) String() string { return proto.CompactTextString(m) }
func (*BlankRequest) ProtoMessage()    {}
func (*BlankRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64925fc78a369f37, []int{1}
}

func (m *BlankRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlankRequest.Unmarshal(m, b)
}
func (m *BlankRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlankRequest.Marshal(b, m, deterministic)
}
func (m *BlankRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlankRequest.Merge(m, src)
}
func (m *BlankRequest) XXX_Size() int {
	return xxx_messageInfo_BlankRequest.Size(m)
}
func (m *BlankRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlankRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlankRequest proto.InternalMessageInfo

// 空白回复
type BlankResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlankResponse) Reset()         { *m = BlankResponse{} }
func (m *BlankResponse) String() string { return proto.CompactTextString(m) }
func (*BlankResponse) ProtoMessage()    {}
func (*BlankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64925fc78a369f37, []int{2}
}

func (m *BlankResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlankResponse.Unmarshal(m, b)
}
func (m *BlankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlankResponse.Marshal(b, m, deterministic)
}
func (m *BlankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlankResponse.Merge(m, src)
}
func (m *BlankResponse) XXX_Size() int {
	return xxx_messageInfo_BlankResponse.Size(m)
}
func (m *BlankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlankResponse proto.InternalMessageInfo

func (m *BlankResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// 存储桶实体
type BucketEntity struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	TotalSize            uint64   `protobuf:"varint,3,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
	FreeSize             uint64   `protobuf:"varint,4,opt,name=freeSize,proto3" json:"freeSize,omitempty"`
	Engine               Engine   `protobuf:"varint,5,opt,name=engine,proto3,enum=file.Engine" json:"engine,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	AccessKey            string   `protobuf:"bytes,7,opt,name=accessKey,proto3" json:"accessKey,omitempty"`
	AccessSecret         string   `protobuf:"bytes,8,opt,name=accessSecret,proto3" json:"accessSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketEntity) Reset()         { *m = BucketEntity{} }
func (m *BucketEntity) String() string { return proto.CompactTextString(m) }
func (*BucketEntity) ProtoMessage()    {}
func (*BucketEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_64925fc78a369f37, []int{3}
}

func (m *BucketEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketEntity.Unmarshal(m, b)
}
func (m *BucketEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketEntity.Marshal(b, m, deterministic)
}
func (m *BucketEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketEntity.Merge(m, src)
}
func (m *BucketEntity) XXX_Size() int {
	return xxx_messageInfo_BucketEntity.Size(m)
}
func (m *BucketEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketEntity.DiscardUnknown(m)
}

var xxx_messageInfo_BucketEntity proto.InternalMessageInfo

func (m *BucketEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BucketEntity) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *BucketEntity) GetTotalSize() uint64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *BucketEntity) GetFreeSize() uint64 {
	if m != nil {
		return m.FreeSize
	}
	return 0
}

func (m *BucketEntity) GetEngine() Engine {
	if m != nil {
		return m.Engine
	}
	return Engine_ENGINE_INVALID
}

func (m *BucketEntity) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *BucketEntity) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *BucketEntity) GetAccessSecret() string {
	if m != nil {
		return m.AccessSecret
	}
	return ""
}

// 对象实体
type ObjectEntity struct {
	Filepath             string   `protobuf:"bytes,1,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Size                 uint64   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Md5                  string   `protobuf:"bytes,4,opt,name=md5,proto3" json:"md5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectEntity) Reset()         { *m = ObjectEntity{} }
func (m *ObjectEntity) String() string { return proto.CompactTextString(m) }
func (*ObjectEntity) ProtoMessage()    {}
func (*ObjectEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_64925fc78a369f37, []int{4}
}

func (m *ObjectEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectEntity.Unmarshal(m, b)
}
func (m *ObjectEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectEntity.Marshal(b, m, deterministic)
}
func (m *ObjectEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectEntity.Merge(m, src)
}
func (m *ObjectEntity) XXX_Size() int {
	return xxx_messageInfo_ObjectEntity.Size(m)
}
func (m *ObjectEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectEntity.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectEntity proto.InternalMessageInfo

func (m *ObjectEntity) GetFilepath() string {
	if m != nil {
		return m.Filepath
	}
	return ""
}

func (m *ObjectEntity) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ObjectEntity) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ObjectEntity) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func init() {
	proto.RegisterEnum("file.Engine", Engine_name, Engine_value)
	proto.RegisterType((*Status)(nil), "file.Status")
	proto.RegisterType((*BlankRequest)(nil), "file.BlankRequest")
	proto.RegisterType((*BlankResponse)(nil), "file.BlankResponse")
	proto.RegisterType((*BucketEntity)(nil), "file.BucketEntity")
	proto.RegisterType((*ObjectEntity)(nil), "file.ObjectEntity")
}

func init() {
	proto.RegisterFile("proto/file/shared.proto", fileDescriptor_64925fc78a369f37)
}

var fileDescriptor_64925fc78a369f37 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xc1, 0xef, 0xd2, 0x30,
	0x1c, 0xc5, 0xdd, 0x8f, 0x31, 0xd8, 0xd7, 0x41, 0x66, 0x63, 0x62, 0x63, 0x3c, 0x2c, 0x8b, 0x87,
	0xc5, 0x03, 0x24, 0x1a, 0xbc, 0x8b, 0x2e, 0x66, 0x51, 0x46, 0xec, 0xc4, 0xab, 0x29, 0xdb, 0x17,
	0x98, 0x8c, 0x0d, 0xd7, 0xee, 0x80, 0x7f, 0xb7, 0x7f, 0x80, 0x69, 0x57, 0xc0, 0xdf, 0xed, 0xbd,
	0xcf, 0x6b, 0xda, 0xf7, 0x96, 0xc1, 0x8b, 0x73, 0xdb, 0xc8, 0x66, 0xbe, 0x2b, 0x2b, 0x9c, 0x8b,
	0x03, 0x6f, 0xb1, 0x98, 0x69, 0x42, 0x6c, 0x85, 0xc2, 0xf7, 0xe0, 0x64, 0x92, 0xcb, 0x4e, 0x10,
	0x02, 0x76, 0xde, 0x14, 0x48, 0xad, 0xc0, 0x8a, 0x86, 0x4c, 0x6b, 0x42, 0x61, 0x74, 0x42, 0x21,
	0xf8, 0x1e, 0xe9, 0x43, 0x60, 0x45, 0x2e, 0xbb, 0xda, 0x70, 0x0a, 0xde, 0xb2, 0xe2, 0xf5, 0x91,
	0xe1, 0xef, 0x0e, 0x85, 0x0c, 0x17, 0x30, 0x31, 0x5e, 0x9c, 0x9b, 0x5a, 0x20, 0x79, 0x0d, 0x8e,
	0xd0, 0x17, 0xeb, 0x0b, 0x9f, 0xbe, 0xf5, 0x66, 0xea, 0xbd, 0x59, 0xff, 0x18, 0x33, 0x59, 0xf8,
	0xd7, 0x02, 0x6f, 0xd9, 0xe5, 0x47, 0x94, 0x71, 0x2d, 0x4b, 0x79, 0x51, 0x2d, 0x6a, 0x7e, 0xea,
	0x5b, 0xb8, 0x4c, 0x6b, 0xf2, 0x1c, 0x86, 0xb2, 0x39, 0x62, 0x6d, 0x3a, 0xf4, 0x86, 0xbc, 0x02,
	0x57, 0x36, 0x92, 0x57, 0x59, 0xf9, 0x07, 0xe9, 0x20, 0xb0, 0x22, 0x9b, 0xdd, 0x01, 0x79, 0x09,
	0xe3, 0x5d, 0x8b, 0xa8, 0x43, 0x5b, 0x87, 0x37, 0xaf, 0xaa, 0x61, 0xbd, 0x2f, 0x6b, 0xa4, 0xc3,
	0xc0, 0x8a, 0xa6, 0xd7, 0x6a, 0xb1, 0x66, 0xcc, 0x64, 0x6a, 0x3b, 0x2f, 0x8a, 0x16, 0x85, 0xa0,
	0x4e, 0xbf, 0xdd, 0x58, 0xf5, 0x32, 0xcf, 0x73, 0x14, 0xe2, 0x0b, 0x5e, 0xe8, 0x48, 0x67, 0x77,
	0x40, 0x42, 0xf0, 0x7a, 0x93, 0x61, 0xde, 0xa2, 0xa4, 0x63, 0x7d, 0xe0, 0x11, 0x0b, 0xb7, 0xe0,
	0xad, 0xb7, 0xbf, 0x30, 0xbf, 0xae, 0x56, 0x6d, 0xcb, 0x0a, 0xcf, 0x5c, 0x1e, 0xcc, 0xf2, 0x9b,
	0x27, 0x3e, 0x0c, 0xba, 0xb6, 0x32, 0xdb, 0x95, 0x54, 0xdf, 0x48, 0xdc, 0x47, 0x6b, 0xad, 0x4e,
	0x9d, 0x8a, 0x85, 0x9e, 0xea, 0x32, 0x25, 0xdf, 0x64, 0xe0, 0xf4, 0x8b, 0x08, 0x81, 0x69, 0x9c,
	0x7e, 0x4e, 0xd2, 0xf8, 0x67, 0x92, 0xfe, 0xf8, 0xf0, 0x35, 0xf9, 0xe4, 0x3f, 0x21, 0x3e, 0x78,
	0x86, 0xad, 0x92, 0x34, 0x59, 0xfb, 0xd6, 0x7f, 0xe4, 0x5b, 0x92, 0x26, 0x1b, 0xff, 0x81, 0x3c,
	0x83, 0x89, 0x21, 0x1f, 0x37, 0xd9, 0xf7, 0xf5, 0xca, 0x2f, 0xb6, 0x8e, 0xfe, 0x77, 0xde, 0xfd,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x63, 0x61, 0x53, 0x5c, 0x56, 0x02, 0x00, 0x00,
}
